name: Build and Test

on:
  workflow_call:

jobs:
  Build-API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: itu-minitwit/Api/Api
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore


  Test-API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: itu-minitwit/Api/
    strategy:
      matrix:
        project:
          - Api.UnitTest
          
    needs: Build-API
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.project }}
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal ${{ matrix.project }}
