version: '3.8'

services:
  itu-minitwit:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    build:
      context: .
      dockerfile: Dockerfile-minitwit
    ports:
      - "8080:5000"
