services:
  postgres:
    image: postgres:14
    container_name: dev_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#    restart: unless-stopped

volumes:
  pgdata:
