global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: codelab-monitor

rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: itu-minittwit-app
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'minitwitapi:5000'
        labels:
          group: production
  - job_name: itu-minittwit-app2
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'http://itu-minitwit:5000/metrics'