@startuml
actor sim
participant api.controller

sim -> api.controller : send messsage "Hello"
activate sim
activate api.controller

api.controller -> api.controller : same as for web

sim <-- api.controller : <<Http no content>> 204
deactivate api.controller

deactivate sim
@enduml