name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  Build-API:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

  Test-API:
    runs-on: ubuntu-latest
    needs: Build-API
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
