name: Commit to pr to main
permissions: write-all

on:
  pull_request:
    branches:
      - main

jobs:
  check-for-warnings:
    uses: ./.github/workflows/jobs/check-for-warnings.yml

  build:
    uses: ./.github/workflows/jobs/build.yml

  test:
    needs: build
    uses: ./.github/workflows/jobs/test.yml
