name: Commit to pr to main
permissions: write-all

on:
  pull_request:
    branches:
      - main

jobs:
  check-for-warnings:
    uses: ./.github/workflows/check-for-warnings.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  simulation:
    needs: test
    uses: ./.github/workflows/run-simulation.yml
    
  sonarqube-analysis:
    needs: test
    uses: ./.github/workflows/sonarqube-analysis.yml
    secrets: inherit
