name: Commit to pr to main
permissions: write-all

on:
  pull_request:
    branches:
      - main

jobs:
  check-for-warnings:
    uses: ./.github/workflows/check-for-warnings.yml

  build:
    uses: ./.github/workflows/build.yml
    
  format:
    uses: ./.github/workflows/format-code.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml
