#Repo for scp 
#https://github.com/appleboy/scp-action
#Repo for SSH
#https://github.com/appleboy/ssh-action
name: Deploy to digitalocean.yml
on:
  workflow_call:
    secrets:
        SSH_HOST:
          required: true
        SSH_USER:
          required: true
        SSH_KEY:
          required: true
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Upload docker-compose.yml to Server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'remote_files/'
          target: '/minitwit/'
          overwrite: true

      - name: Deploy Application via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
            DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DB_CONNECTION_STRING
          script: |
            cd /minitwit
            ./deploy.sh
