name: Build

on:
  workflow_call:

jobs:
  API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: itu-minitwit/Api/Api
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Format
        run: dotnet format
  
