name: Release and deploy
permissions: write-all

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-tag:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/Create-tag-on-merge.yml

  check-for-warnings:
    if: github.event.pull_request.merged == true
    needs: create-tag
    uses: ./.github/workflows/check-for-warnings.yml

  build:
    if: github.event.pull_request.merged == true
    needs: create-tag
    uses: ./.github/workflows/build.yml

  test:
    if: github.event.pull_request.merged == true
    needs: build
    uses: ./.github/workflows/test.yml

  create-release:
    if: github.event.pull_request.merged == true
    needs: [check-for-warnings, test]
    uses: ./.github/workflows/create-release.yml

  create-docker-image:
    if: github.event.pull_request.merged == true
    needs: [check-for-warnings, test]
    uses: ./.github/workflows/create-docker-image.yml

  deploy-to-digitalocean:
    if: github.event.pull_request.merged == true
    needs: create-docker-image
    uses: ./.github/workflows/deploy-to-digitalocean.yml