name: Release and deploy
permissions: write-all

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check-for-warnings:
    uses: ./.github/workflows/check-for-warnings.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  create-tag:
    needs: [check-for-warnings, test]
    uses: ./.github/workflows/Create-tag-on-merge.yml

  create-release:
    needs: create-tag
    uses: ./.github/workflows/create-release.yml

  create-docker-image:
    needs: [check-for-warnings, test]
    uses: ./.github/workflows/create-docker-image.yml

  deploy-to-digitalocean:
    needs: create-docker-image
    uses: ./.github/workflows/deploy-to-digitalocean.yml
